### ISSUE TITLE
If I want to launch ScummVM core, Retroarch crashes

### ISSUE THREAD

**Issue by NerosTie** [libretro-mirrors/scummvm#11]
My ScummVM core comes from the "Online Updater" menu.  

If I load the core, Retroarch crashes and it gives me this error:

`retroarch: symbol lookup error: /home/Neros/Jeux/Retroarch/Cores/scummvm_libretro.so: undefined symbol: _Z13path_is_validPKc`

**Comment by inactive123** [comment]
Yeah, it's a known linking error. We are trying to look into it.

**Comment by inactive123** [comment]
Should be fixed now thanks to @Alcaro and some minor contributions by me. Can you git pull the latest sources and check if it works now on your end?

**Comment by NerosTie** [comment]
I could but I don't know how to compile scummvm to build a libretro (I'm on Linux)

**Comment by inactive123** [comment]
I guess you have to wait for the next nightly core then.

**Comment by NerosTie** [comment]
It works now. Thank you!
