### ISSUE TITLE
[Wii U] "Close Content" freezes RA

### ISSUE THREAD

**Issue by cucholix** [libretro-mirrors/scummvm#116]
Hi,

When you open whatever game on ScummVM it plays fine, but if you go to Quick Menu > Close content , it will freeze RA and you'll need a hardware restart.

**Comment by hhromic** [comment]
This seems to happen not only for WiiU but also for RPI and Android builds (see <https://retropie.org.uk/forum/topic/19693/lr-scummvm-request-for-comments-and-testing/6>).

If you try to quit using "RetroArch RGUI -> Quit Retroarch", which probably in turn it first does "Close content", then RA freezes. If you quit using ScummVM's own internal menu, the core closes fine and then you can quit normally from RA. No crashes.

From the forum posts, in Android the crash seems to be easier to reproduce (happens always). On the RPI, seems to be more random. Probably is not a platform-specific problem, and maybe is a race condition somewhere.

**Comment by hhromic** [comment]
Here is some more insights about this issue. I tested on a Raspberry Pi 2 and with two games: Beneath a Steel Sky and Indiana Jones and the Fate of Atlantis.

When it crashes/freezes, you can login via ssh and kill the retroarch process (`skill -KILL retroarch`) and you will get control back. When frozen, retroarch also doesn't respond to the SIGTERM signal (`skill retroarch` or `skill -TERM retroarch`). No segfaults nor exceptions reported, it just freezes.

The verbose logging (`--verbose`) is not very informative either. When it freezes it just stops at the "unloading game" operation:

      :
    [INFO] [GL]: VSync => on
    [INFO] [EGL]: eglSwapInterval(1)
    [INFO] Unloading game..

And when it doesn't freeze, it gracefully finishes the shutdown:

      :
    [INFO] [GL]: VSync => on
    [INFO] [EGL]: eglSwapInterval(1)
    [INFO] Unloading game..
    [INFO] Unloading core..
    [INFO] Unloading core symbols..
    [INFO] Saved core options file to "/opt/retropie/configs/all/retroarch-core-options.cfg"

So it looks it crashes when trying to "unload the game". Also I found out that it happens more often if you are starting the game (e.g. the publisher logo screen or even the ScummVM splash screen) than after running it for a while. However it still happens sometimes (but more rarely) later in the game.

Furthermore, apparently it doesn't happen when you send a SIGTERM signal to quit retroarch, which also triggers the unload game, core, symbols, etc. normally. Therefore, it seems to happen only when you quit either via Hotkey+Start exit combo or the "close content" option in the RGUI.

Apart from this issue, the core is running very nicely and without issues.

**Comment by hhromic** [comment]
A bit more. If you use the "Close Content" menu option in RGUI, you get this in the verbose log when it freezes/crashes (and still hangs at "unloading game"):

    [INFO] [GL]: VSync => on
    [INFO] [EGL]: eglSwapInterval(1)
    [INFO] No content, starting dummy core.
    [INFO] arg #0: retroarch
    [INFO] arg #1: --menu
    [INFO] arg #2: -c
    [INFO] arg #3: /opt/retropie/configs/scummvm/retroarch.cfg
    [INFO] Unloading game..

**Comment by hhromic** [comment]
I think I found a solution to the freeze-on-quit problem. We are testing a patch in the RetroPie forum and if confirmed working, will submit a PR.
https://retropie.org.uk/forum/topic/19693/lr-scummvm-request-for-comments-and-testing
