### ISSUE TITLE
Is MT-32 (munt) midi emulation available in this scummvm core?

### ISSUE THREAD

**Issue by thorias** [libretro-mirrors/scummvm#117]
Is MT-32 (munt) midi emulation available in this scummvm core port?
If not, is it possible to add it in the compilation of the core?

Thanks for the reply.

**Comment by i30817** [comment]
I'd be surprised if not, because scummvm bundles the library in their repository.

**Comment by thorias** [comment]
Yeah it does, I already figured it out!

Thanks,
