### ISSUE TITLE
Compressed audio (flac, ogg...) doesn't work

### ISSUE THREAD

**Issue by NerosTie** [libretro-mirrors/scummvm#12]
There is no audio in scummvm-libretro when the audio is compressed such as flac or ogg.

e.g: Loom CD DOS VGA version (same for all CD version actually).

Is it a known bug? If yes, why?

Thank you!

**Comment by RobLoach** [comment]
Confirmed.

**Comment by diablodiab** [comment]
Scummvm needs to be compiled with support for Vorbis support for this to work.
Which platform are you on?

**Comment by NerosTie** [comment]
@diablodiab I'm on ArchLinux and using this package for Retroarch: https://aur.archlinux.org/packages/retroarch-git.
ScummVM comes from the "Online Update -> Core Updater" in Retroarch.

**Comment by RobLoach** [comment]
Are `libogg-dev libvorbis-dev` something we'd add to https://github.com/libretro/libretro-super/ to have it build correctly?

**Comment by diablodiab** [comment]
You will need to have some libraries installed and also some parameters added to the Makefile:

For Windows/Linux/OSX you need ogg and vorbis and these additions to the Makefile:
DEFINES += -DUSE_VORBIS
LDFLAGS += -lvorbis -logg -lvorbisfile

For Android you need ogg and tremor:
DEFINES += -DUSE_VORBIS -DUSE_TREMOR
LDFLAGS += -lvorbisidec

If you are using the ScummVM tools to compress resource files you will also need to add zip-support:
LDFLAGS += -lz

**Comment by NerosTie** [comment]
@diablodiab what Makefile? Retroarch in AUR or the ScummVM-libretro core?  
(Also, i'm using the "normal" ScummVM 1.7.0 and everything is good)

**Comment by diablodiab** [comment]
The Makefile in the ScummVM libretro core:
./backends/platform/libretro/build/Makefile

**Comment by NerosTie** [comment]
Any news about this? To know if I can close it or not.

**Comment by diablodiab** [comment]
It's addressed for the Android builds but not other builds as far as I know.

**Comment by lollo78** [comment]
Hi guys, 
I compiled ScummVM for my RPi3 (with LibreELEC 7.0.1) cloning the LibreELEC git branch 7.0.1 and using this package.mk: https://github.com/escalade/LibreELEC.tv/blob/emu/packages/escalade/emulation/scummvm-libretro/package.mk

This system is so simple. 
Changing PKG_VERSION with the latest SHA commit, I can quickly compile and test the new versions (PROJECT=RPi2 ARCH=arm scripts/build scummvm-libretro).

I tried also with a2b6276 commits, but the speech in my games (compressed in FLAC with ScummVM Tools) doesn't work.

It's a bug in ScummVM or I have to modify this package.mk to compile it with flac and vorbis support?
Thx

**Comment by lollo78** [comment]
Hi, I tried to fork scummvm repo, modify Makefile like recommended by @diablodiab 
https://github.com/lollo78/scummvm/blob/master/Makefile
but audio doesn't work.
I done right the mods?

**Comment by diablodiab** [comment]
You need to edit the Makefile under:
backends/platform/libretro/build/Makefile

I haven't compiled it for Linux in a while, but I believe these are the lines you need to edit:
https://github.com/lollo78/scummvm/blob/master/backends/platform/libretro/build/Makefile#L33-L34

**Comment by lollo78** [comment]
Hi diablodiab. 
I'm trying to compile it for Raspberry Pi2/3 using Ubuntu 16.04 LTS.
Untill now I used always your scummvm_libretro.so extracted from your Openelec distro. And it works fine with games compressed with Scummvm Tools. But now I would like to update it.

**Comment by diablodiab** [comment]
Then it might be this section of the Makefile:
https://github.com/lollo78/scummvm/blob/master/backends/platform/libretro/build/Makefile#L111

(you will have to add the LDFLAGS line)

But try both suggestions, I'm not sure if the buildroot system you are using uses the unix or arm section of the Makefile.

**Comment by lollo78** [comment]
we posted at the same time (I edited the post above) :D
To use games compressed with ScummVm Tools I have to add vorbis, mad, zlib and flac? 
Could you tell me the right syntax to enable this in DEFINES and LDFLAGS please?
`
DEFINES += -fPIC -Wno-multichar -lvorbis -logg -lvorbisfile -lz -lmad`

**Comment by diablodiab** [comment]
In the end it depends on the buildroot system being used by LibreElec. Some libraries might not be available - I remember something about mad not being available in OpenElec.

I only have experience with using zlib and vorbis, I suggest you try with those and stick with those formats in the ScummVM tools.

(this is from memory, so if this doesn't work you will need to tamper with it on your own)

If we use these lines as example:
https://github.com/lollo78/scummvm/blob/master/backends/platform/libretro/build/Makefile#L33-L34

You will have to add the stuff I wrote about above so they become:
DEFINES += -fPIC -DUSE_VORBIS
LDFLAGS += -shared -Wl,--version-script=../link.T -fPIC -lvorbis -logg -lvorbisfile -lz

Same with the lines in the "arm" section of the Makefile - add to the existing lines or create the line (LDFLAGS for example) if it doesn't exist.

Remember to use +=

**Comment by lollo78** [comment]
https://github.com/lollo78/scummvm/blob/master/backends/platform/libretro/build/Makefile#L108-L112
but still not work.
In line 108 it specify "armv", but I compile with
PROJECT=RPi2 ARCH=arm scripts/build scummvm-libretro

If I try to compile with ARCH=armv 
I have this error:

```
================================================================================
 ERROR: Architecture not found, use a valid Architecture
 for your project or create a new config
================================================================================

 Valid Architectures for your project: RPi2
 - arm
 - conf
 - armv

```

I'll try with L33-L34

**Comment by diablodiab** [comment]
I'm sorry but it's been too long since I compiled Openelec and similar for me to remember the mechanics.

**Comment by lollo78** [comment]
EUREKA!!!!!
The mod in "unix" platform solve the issue:
https://github.com/lollo78/scummvm/blob/master/backends/platform/libretro/build/Makefile#L33-L34
You are my idol diablodiab!
Thank you very much!
:+1:

**Comment by lollo78** [comment]
Just a little consideration.
Why this "fix" is not included in master code?

**Comment by diablodiab** [comment]
Linking to external libraries such as vorbis could cause problems on platforms that don't have them.

**Comment by inactive123** [comment]
We could bake dependencies like libvorbis inside the core. If that is something you would like to look at and make happen, I would be happy to merge the pull request.

**Comment by diablodiab** [comment]
I can look into it. I'm planning on looking into the autostart-not-working problem anyway.

**Comment by lollo78** [comment]
It could be so cool! 
Thanks guys
:\*

**Comment by NerosTie** [comment]
So, it works now? :)

**Comment by diablodiab** [comment]
Ogg Vorbis support is working. Flac and MP3 is not.

**Comment by MrXCuci** [comment]
Doesn't seem to work on Android either (only tested FLAC): http://wiki.scummvm.org/index.php/Compiling_ScummVM/Android
