### ISSUE TITLE
Adjustable mouse speed

### ISSUE THREAD

**Issue by Phiben** [libretro-mirrors/scummvm#123]
When using an actual mouse, not a controller’s analogue sticks, the mouse cursor is way to fast.

I think it would be a big improvement for the scummvm core, if the mouse speed could be adjusted from within the core settings.

**Comment by RobLoach** [comment]
Is the Pointer Speed option only available on the other menu system? Perhaps that's something we could add to the libretro core options.

![screenshot at 2019-01-06 02-53-52](https://user-images.githubusercontent.com/25086/50733596-53adae00-115e-11e9-99c6-3c7516906c16.png)


The RetroArch mouse pointer is handled different than a libretro core speed. If you go Fullscreen, the reference is a bit more manageable.

**Comment by Darknior** [comment]
It's the only problem of this libretro core i LOVE !!!!
We lost the emulator menu to configure games, graphics, control with mouse, audio lib ....
Is it possible to add these options to libretro ? Or to let us how the original menu to configure games ?
For the moment the only solution, is to configure games wit the original emulator, to generate the ini file, and after launch the game with this core.

**Comment by jdgleaver** [comment]
I know I'm a bit late, but I only noticed this issue a couple of hours ago...

PR #127 adds a new 'Mouse Speed' core option which should make 'real' mice fully usable.

> We lost the emulator menu to configure games, graphics, control with mouse, audio lib ....

No, we still have the ScummVM menu!

Please check the documentation: https://docs.libretro.com/library/scummvm/

**Comment by hhromic** [comment]
@Darknior , yes the menu is still there!  Just press START in your gamepad to access it during game.
However, for it to retain settings, you must add the game first to `scummvm.ini`, with a given path as minimum. Then you will be able to set and retain any settings from the UI.
I will be later working on an easier method to customise game settings in RetroPie (if that is what you are using).

**Comment by RobLoach** [comment]
Interesting... Older versions of Scummvm core did have this appear in the core options. Latest master seems to not have any core options?

**Comment by jdgleaver** [comment]
@RobLoach ???

There were no core options until I added them back in May. These included options to configure gamepad cursor control, but not mouse speed. Latest master has all the old options intact.

Or are you referring to the 'Control' tab of the internal ScummVM menu? I don't think we've ever had that - it looks like it's only wired up for the (stand-alone) SDL build. I'm not sure we'd want it, anyway - it's more convenient to handle this sort of thing on the libretro side!  :slightly_smiling_face:

**Comment by RobLoach** [comment]
Load Core --> ScummVM --> Quick Menu --> Options

![screenshot at 2019-01-14 11-33-05](https://user-images.githubusercontent.com/25086/51126066-32009680-17f0-11e9-9baf-7ca7677bd786.png)

**Comment by jdgleaver** [comment]
Oh, I see - that's because you're loading the core without starting it!

This is what you get in-game (or after selecting Load Core > Start Core):

![screenshot_2019-01-14_16-42-24](https://user-images.githubusercontent.com/38211560/51126783-e7950f00-181b-11e9-810e-bc8e3ba23c57.png)

**Comment by RobLoach** [comment]
That worked! Thanks a lot.

**Comment by hhromic** [comment]
The mouse speed option has been merged now, @Phiben  can you test and report back so the issue can be closed? Thanks!

**Comment by Phiben** [comment]
I'd love to test as soon as the core is updated at buildbot.libretro.com.

**Comment by Phiben** [comment]
The core (x86_64) still hasn't been updated at buildbot.libretro.com. I think I just have to wait?

**Comment by jdgleaver** [comment]
Hmm... it looks like there's something wrong here. Linux, Android, etc. are fine, but the last Windows (x64) build is dated 2018-12-03.

So I guess the Windows builds started failing after commit 7f39a7fada991d59b902db3b7672ffa8c7f54e7d?

I don't have the means to compile for Windows, so I can't debug this. Does anyone else have any suggestions...?

**Comment by jdgleaver** [comment]
@twinaphex Sorry to bother you, but it seems the Windows builds of the scummvm core are failing to compile since the updates in commit 7f39a7fada991d59b902db3b7672ffa8c7f54e7d. Would you maybe have time to take a quick look at this? (I don't know how to view the build logs, nor do I know much about Windows, otherwise I'd try to do something myself...)

**Comment by hhromic** [comment]
The Windows build seems to be failing after changing `LD` from `$(CXX)` to `$(CC)` and hitting unresolved symbols. In Linux you get the same errors if you force `-Wl,--no-undefined`. Looks like in Windows the linker does not like undefined symbols.

The linker command invoked in buildbot is:
```
gcc -shared -static-libgcc -static-libstdc++ -s -Wl,--version-script=../link.T ../../../../backends/platform/libretro/libretro.o ../../../../backends/platform/libretro/os.o ../../../../backends/platform/libretro/libretro-common/libco/libco.o ../../../../backends/platform/libretro/libretro-common/file/retro_stat.o base/libbase.a engines/scumm/libscumm.a engines/access/libaccess.a engines/adl/libadl.a engines/agi/libagi.a engines/agos/libagos.a engines/avalanche/libavalanche.a engines/bbvs/libbbvs.a engines/cge/libcge.a engines/cge2/libcge2.a engines/cine/libcine.a engines/composer/libcomposer.a engines/cruise/libcruise.a engines/draci/libdraci.a engines/drascula/libdrascula.a engines/dreamweb/libdreamweb.a engines/fullpipe/libfullpipe.a engines/gnap/libgnap.a engines/gob/libgob.a engines/groovie/libgroovie.a engines/hopkins/libhopkins.a engines/hugo/libhugo.a engines/kyra/libkyra.a engines/lab/liblab.a engines/lastexpress/liblastexpress.a engines/lure/liblure.a engines/made/libmade.a engines/mads/libmads.a engines/mohawk/libmohawk.a engines/mortevielle/libmortevielle.a engines/neverhood/libneverhood.a engines/parallaction/libparallaction.a engines/pegasus/libpegasus.a engines/plumbers/libplumbers.a engines/queen/libqueen.a engines/saga/libsaga.a engines/sci/libsci.a engines/sherlock/libsherlock.a engines/sky/libsky.a engines/sword1/libsword1.a engines/sword2/libsword2.a engines/sword25/libsword25.a engines/teenagent/libteenagent.a engines/tinsel/libtinsel.a engines/toltecs/libtoltecs.a engines/tony/libtony.a engines/toon/libtoon.a engines/touche/libtouche.a engines/tsage/libtsage.a engines/tucker/libtucker.a engines/voyeur/libvoyeur.a engines/wintermute/libwintermute.a engines/zvision/libzvision.a gui/libgui.a backends/libbackends.a engines/libengines.a video/libvideo.a image/libimage.a graphics/libgraphics.a audio/libaudio.a common/libcommon.a audio/softsynth/mt32/libmt32.a libdeps.a  -o scummvm_libretro.dll
```

I'm not sure if the correct fix is to set `LD` back to `$(CXX)` because this is a mixed C/C++ codebase, or for Windows add a linker flag to ignore the undefined symbols (that are resolved in runtime).

Edit: I currentl don't have a Windows build system to test, unfortunately.
Edit2: the buildbot output log is here: http://p.0bl.net/81475

**Comment by jdgleaver** [comment]
Hey, that's really good of you to investigate this.

Windows is a mystery to me, but since `LD` always used to be `$(CXX)` then I guess changing it back would do no harm...?

I think @twinaphex should have the final say here, since he made the commit...  :wink:

**Comment by hhromic** [comment]
@jdgleaver , managed to setup a Windows build environment. It is way easier than expected :)

So, I can confirm that indeed restoring `LD = $(CXX)` solves the build for Windows as well. I will be sending a PR now with the build-fix. Hopefully it can get merged soon and the buildbot can generate a binary for Windows.

Ref: https://github.com/libretro/scummvm/pull/128

**Comment by jdgleaver** [comment]
@hhromic That's excellent! Thanks for fixing this  :slightly_smiling_face:

**Comment by hhromic** [comment]
Looking forward for the merge and see how it goes :)

**Comment by Phiben** [comment]
I don't mean to be pushy, but who is in charge to merge the pull requests?

**Comment by RobLoach** [comment]
Pinged... Buildbot should be building things, let's leave this open and test once it's build. Thanks a lot for the hard work, all!

**Comment by hhromic** [comment]
@RobLoach thanks for the heads-up.  I just discovered another (simple hopefully) build error for ios/ios9 devices, that I now addressed in a new PR. Should not affect other builds.

However, I'm puzzled on the inner workings of the libretro buildbot. Any of you guys know how the tasks are scheduled by the buildbot? I saw a few scummvm jobs in the buildbot Discord channel but not all of them (neither failed nor done). For example Windows 32bits and OSX 64bits are "done", the aforementioned ios platforms are "failed", however the other plaforms (linux32/64, win64, armv7, android) have not been reported yet.

I don't know how to check if they are scheduled and yet to be built or something went wrong.  Thanks for any info!

**Comment by RobLoach** [comment]
Seeing iOS failures:
http://p.0bl.net/86233

Buildbot goes. Just takes a while since there's a lot of tasks. If you ask for the password in Discord, we could give it to you.

**Comment by hhromic** [comment]
> Seeing iOS failures:
> http://p.0bl.net/86233

Yup, sent a new PR to hopefully address that: #133 

> Buildbot goes. Just takes a while since there's a lot of tasks.

Allrighty then, so just patience is needed. No problem, I just didn't know how it is setup.

>  If you ask for the password in Discord, we could give it to you.

That could be useful indeed. Later, when I have a bit more free time I will certainly do that.

Thanks for the info!

**Comment by hhromic** [comment]
New builds are fresh out of the oven now!
```
<retrobot> scummvm: [status: done] [recipes/android/cores-android-jni]
<retrobot> scummvm: [status: done] [recipes/apple/cores-osx-x64-generic]
<retrobot> scummvm: [status: done] [recipes/linux/cores-linux-arm7neonhf]
<retrobot> scummvm: [status: done] [recipes/linux/cores-linux-armhf-generic]
<retrobot> scummvm: [status: done] [recipes/linux/cores-linux-x64-generic]
<retrobot> scummvm: [status: done] [recipes/nintendo/libnx]
<retrobot> scummvm: [status: done] [recipes/nintendo/wiiu]
<retrobot> scummvm: [status: done] [recipes/windows/cores-windows-x64_seh-generic]
<retrobot> scummvm: [status: done] [recipes/windows/cores-windows-x86_dw2-generic]
<retrobot> scummvm: [status: fail] [recipes/apple/cores-ios9-generic] LOG: http://p.0bl.net/86231 Last good build: N/A
<retrobot> scummvm: [status: fail] [recipes/apple/cores-ios-generic] LOG: http://p.0bl.net/86233 Last good build: N/A
```
Pinging @Phiben, try to update and verify that the mouse speed option is there. Please report back any feedback. Hope the new option helps you!

The two failing builds (ios/ios9) should be addressed by the current open PR, hopefully gets merged soon as well. This would bring all the builds of scummvm to a green status \o/

**Comment by Phiben** [comment]
I've just tested it and it works like a charm!! A big improvement for the core.

Thank you @jdgleaver @hhromic and everyone else involved!

**Comment by hhromic** [comment]
Glad to hear @Phiben ! thanks to you for reporting and testing, after all you motivated this improvement in the first place :)
