### ISSUE TITLE
Kyra.dat is not recognized

### ISSUE THREAD

**Issue by DukeSkinny** [libretro-mirrors/scummvm#126]
Games using the Kyra engine and thus relying on the kyra.dat file won't launch, whether kyra.dat is in the game directory, RA's system dir, system/scummvm, or system/scummvm/extra.

**Comment by ahnernoch** [comment]
same here. Couldn't find a working solution.

**Comment by Mr-Jake** [comment]
Did the recent 2.1.0 core update fix this issue, or is it still not working?

**Comment by DukeSkinny** [comment]
Working beautifully on my end now.
