### ISSUE TITLE
[RFC] Fixing close freeze issue

### ISSUE THREAD

**Issue by hhromic** [libretro-mirrors/scummvm#129]
It has been reported multiple times that when closing content from RetroArch instead of the internal ScummVM menu, the system freezes. An example report is #116. I have seen similar reports in the libretro forums and in the RetroPie forums. Reportedly this happens on ARM and Android builds. This happens to myself also in RaspberryPi so is not an isolated issue.

The issue in a nutshell is this:
* Games launch and work fine during gameplay
* If you close the game using the ScummVM internal menu, you get back to RetroArch and no issues
* If you close the game from RetroArch, e.g. using EXIT combo on gamepad or using the Close Content functionality from the menu, at random times the system "freezes" and you have to kill RetroArch manually. It is randomly triggered without trying more than two or three times.

I investigated the issue and turns out that RetroArch doesn't crash or freezes, but falls in an endless loop while closing in this block:
https://github.com/libretro/scummvm/blob/d6fb141ed00c70fd84cf78386e88c244265a14f1/backends/platform/libretro/libretro.cpp#L460-L464

This because the `EMULATORexited` flag is never set to `true` in here:
https://github.com/libretro/scummvm/blob/d6fb141ed00c70fd84cf78386e88c244265a14f1/backends/platform/libretro/libretro.cpp#L96-L97

And this happens because the main `scummvm` function never quits. Because it fails to close randomly and not *every time*, I assume there is a race condition going on.

I further investigated the quit mechanism and found out that the following proposed patch fixes the issue and it never freezes while quitting from RetroArch:
```diff
diff --git a/backends/platform/libretro/os.cpp b/backends/platform/libretro/os.cpp
index c37171e..eb4c222 100644
--- a/backends/platform/libretro/os.cpp
+++ b/backends/platform/libretro/os.cpp
@@ -1212,7 +1212,7 @@ class OSystem_RETRO : public EventsBaseBackend, public PaletteManager {
       {
          Common::Event ev;
          ev.type = Common::EVENT_QUIT;
-         _events.push_back(ev);
+         ((OSystem_RETRO*)g_system)->getEventManager()->pushEvent(ev);
       }
 };
```
Apparently sending the `QUIT` event directly to the event manager instead of using the buffer `_events` queue like with the keyboard/mouse events avoids the race condition. This solution is impemented temporarily in the RetroPie build of the core and users seem happy so far with it, without any other side effects.

I didn't write the original code, so I humbly and kindly want to ask the senior devs of this core I believe may know something, i.e. @ehmry and @jdgleaver, for why the buffer `_events` queue is necessary and why not the events are sent directly?
Also I would like your thoughts about the proposed solution so I send a PR upstream.

**Comment by ghost** [comment]
Sounds good to me, I'm not a senior dev but from what I have seen `_events` violates ScummVM conventions and should go should go away because it is a global C++ object that requires construction during core loading.

**Comment by hhromic** [comment]
Thanks for your reply @ehmry , much appreciated!
Sorry for my labelling, with "senior" I tried to mean devs that worked on this core before. You previously committed the exit loop in 7c933534, so I assumed you might be familiar with that code.

I also agree with you that the `_events` queue seems very hacky somehow. But if you think my proposed patch is okay then I will just send that for now (after waiting for more comments) and later investigate better how `_events` work and how if it can be improved.

Thanks again for your feedback.

**Comment by jdgleaver** [comment]
I'm not a senior dev either... :slightly_smiling_face: 

But I do remember that when I fixed the major timing issues with the core, I noticed that parts of the libretro-specific code were dubious and not well tested. These 'freeze on exit' errors did not happen at all when I last did any significant work back in May last year, but I did fix some other 'infinite loop' lock ups. It would not surprise me if @ehmry's libco updates and clean-ups (#118) exposed more old legacy bugs in the existing code.

I think @ehmry knows more about ScummVM than me, so I'd listen to him if he says the current `_events` system should be depreciated.

@hhromic Your patch looks perfectly sensible to me. I would go ahead and submit the PR.

**Comment by hhromic** [comment]
Thanks for the feedback @jdgleaver , also appreciated!
Again, sorry for using the word "senior" so freely here, I meant devs with experience in this core :)

Yes I agree that definitively the libretro bits and bolts of this core seemed to be done in a rush and not well tested, however it works :)   Later this year I will become a bit more free to work on hobbies and I would like to help on bringing the ScummVM core to a more mature state. For example update/clean the libretro-specific code and later update ScummVM itself to be more current and easy to maintain.

Thanks for all the feedback guys, I will go ahead and submit the PR. Hopefully gets merged soon together with the other PR that fixes the build for Windows. Cheers!

**Comment by jdgleaver** [comment]
> Later this year I will become a bit more free to work on hobbies and I would like to help on bringing the ScummVM core to a more mature state. For example update/clean the libretro-specific code and later update ScummVM itself to be more current and easy to maintain.

This would be wonderful! Thank you in advance, and I wish you the best of luck!

**Comment by ghost** [comment]
Yes, this would be great. The ScummVM core meets my odd portability requirements better than the standard build, so I would also like to see improvements, and possibly the Libretro backend merged upstream. If you are interested in clean-up, I recommend reading the [ScummVM coding conventions](https://wiki.scummvm.org/index.php?title=Coding_Conventions), I think these rules should apply to the core code as well.

**Comment by hhromic** [comment]
Thanks for the heads-up @ehmry !
I was thinking on properly porting the libretro components (for example events) as real backend implementations in ScummVM, like recently @ccawley2011 did for the FS backend.  I can't wait to have more time to play with this :)
