### ISSUE TITLE
Default Directory is /

### ISSUE THREAD

**Issue by jet082** [libretro-mirrors/scummvm#144]
The default directory when finding folders (for extras content, games, etc) is /

While this is not a problem in many environments, it is in iOS as directories listed in / will not list their children if you cd into them. However, you can still change to particular directories your application has access to.

As a result, it would be best if, at least for iOS, the core configured its default browse path to the retroarch directory.

**Comment by jet082** [comment]
Currently, you need to manually edit the paths in the ini file. The paths take ~, so it is not too bad, but still very unnecessary.

**Comment by Dobbelklick** [comment]
Why was this closed?
