### ISSUE TITLE
Can't use themes - RA 1.8.4, ScummVM 2.1.0

### ISSUE THREAD

**Issue by mantheman** [libretro-mirrors/scummvm#157]
Retroarch 1.8.4 on i386, Ubuntu 14.04 (with backported toolchain since gcc 4.8 won't build RA after 1.7.3 or so). I checkout [this commit](https://github.com/libretro/scummvm/commit/0c777c88c556e21acb9a0772790c7519acf499c6) which is from nov 24, 2019. and the most recent commit as of now. I'm not sure when this happened, but it used to work a couple of months ago at least.

Scummvm doesn't recognize themes. Only the green text mode gui shows up.
It won't list the themes either except the built-in classic theme, which doesn¨t work either. I've tried just zips, folder and zips+folder in the theme folder. It is the same whether I install from the PPA (testing) or build my own.

**Comment by RobLoach** [comment]
Docs cover themes:
https://docs.libretro.com/library/scummvm/#usage

**Comment by mantheman** [comment]
Issue can be closed. Worked after I extracted the latest scummvm.zip.
