### ISSUE TITLE
Game configurations in scummvm.ini don't work

### ISSUE THREAD

**Issue by rtomasa** [libretro-mirrors/scummvm#164]
Hi,

I'm using the **libretro** version of **ScummVM 2.1.0** from retropie system in a Raspberry Pi 3. My Retroarch is in v1.8.5.

I'm also using .svm files for launching games, i.e: `./roms/scummvm/dott/tentacle.svm` and works perfectly.
The problem comes when I'm trying to apply any special configuration for any game. The configuration in the retropie distro is placed in `./BIOS/scummvm.ini` and I'm sure that it is working because making any change in the `[scummvm]` section works fine, but if I add new sections per game i.e.`[tentacle]` the configs are not taken into consideration.

So, is this really a bug or am I doing something wrong?

BR

**Comment by HVR88** [comment]
Use the ScummVM UI to make a change to the settings while a game is running, quit and then see if the changes have been written to the ini file.  Make sure you're looking in the correct [section]
