### ISSUE TITLE
USB to MIDI Support

### ISSUE THREAD

**Issue by rtomasa** [libretro-mirrors/scummvm#166]
Hi,

maybe this not a bug nor any issue but I wanted to confirm if the ScummVM libretro port supports real external MIDI devices via USB to MIDI cable. In the stand alone version of Windows is available from Options > Sound > Default device dropdown. I think this could be an expected limitation of the libretro audio source fonts, but I wanted to confirm.

I've tested in Raspberry Pi3 + Raspbian Lite (Stretch) with Retroarch 1.9.0 and lr-scummvm 2.1.0

BR

**Comment by gouchi** [comment]
Hi,

You should check first in the kernel config that at least those configs are enabled 

```
CONFIG_SND_SEQUENCER=m
CONFIG_SND_RAWMIDI_SEQ=m
```

Thank you.

**Comment by rtomasa** [comment]
Sorry, it's been long time from your comment. The second config param does not exists in the Kernel config but I have a similar one:
```
CONFIG_SND_SEQUENCER=m
CONFIG_SND_RAWMIDI=m 
```

Regards

**Comment by rtomasa** [comment]
Closing this old issue since as of today it works fine
