### ISSUE TITLE
Can we use the virtual keyboard through the libretro core?

### ISSUE THREAD

**Issue by DrUm78** [libretro-mirrors/scummvm#181]
I did not manage to get the virtual keyboard activated and appearing with the libretro core, anyone managed to do it?
I included it in "/base/main.cpp":
```
ConfMan.set("vkeybdpath", "/opk/extra", Common::ConfigManager::kApplicationDomain);
ConfMan.set("vkeybd_pack_name", "vkeybd_small", Common::ConfigManager::kApplicationDomain);
```
I tried to bind some keys (SDL or Linux keycodes) to some various virtual keyboard activation events through the whole code but in vain.
This documentation seems to be only for the native port: https://wiki.scummvm.org/index.php/Virtual_Keyboard and this method does not work (binding a key to "Common::KEYCODE_F7" event) as I use this sdlretro frontent to load the core and send the keycode inputs: https://github.com/FunKey-Project/sdlretro

I tend to think that's it's not possible at the moment through a libretro frontend, am I wrong?

Thanks!

**Comment by spleen1981** [comment]
Virtual keyboard is available in [ScummVM mainline libretro core](https://github.com/spleen1981/scummvm-mainline-libretro), included in current Lakka master.

**Comment by DrUm78** [comment]
Very nice, it works, thanks. 👍
