### ISSUE TITLE
Bundle kyra.dat with SCUMMVM core

### ISSUE THREAD

**Issue by mrmatteastwood** [libretro-mirrors/scummvm#182]
**Steps to Reproduce:**
1. Grab Linux SCUMMVM build from Jul 15, 2021: https://github.com/libretro/scummvm/issues/179#issuecomment-880923717
2. Place in RetroArch (Linux) 1.9.6 Cores directory
3. Launch RA > Launch SCUMMVM Core > Launch Legend of Kyrandia

**Expected Results:**
Legend of Kyrandia should run.

**Current Results:**
SCUMMVM throws up an error message saying kyra.dat is missing.

**Background:**
This is a legacy issue. In order to play Legend of Kyrandia, one has to find the correct kyra.dat file for whatever SCUMMVM version is currently in RetroArch:
https://linux.goeszen.com/kyra-dat-not-found-or-corrupted-running-kyrandia-via-scummvm-on-ubuntu.html
Then, this file needs to go into the "extras" directory inside SCUMMVM's system directory in RA's system directory.
If at all possible, it would be great to package kyra.dat with the SCUMMVM core going forward, or adding information on the SCUMMVM documentation page on how to acquire that file and where to put it.

**Notes:**
- Issue encountered on Linux Mint 20.2 running RA 1.6.0, using @diablodiab's build of SCUMMVM 2.3.0 for Linux from Jul 15, 2021.
- However, this issue also occurs in previous versions of the SCUMMVM core and most likely across all platforms (Windows etc.).

**Comment by DrUm78** [comment]
That's not an issue, extra engine data are meant to be external to the Libretro core itself and are packed here so you can copy them yourself wherever you want:
https://github.com/libretro/scummvm/blob/master/backends/platform/libretro/aux-data/scummvm.zip

You can then point to them through ScummVM menu ("Extra Path" in "Paths" section) or modify the code to redirect to them by default.

**Comment by mrmatteastwood** [comment]
Ah, this is good to know. Somehow, that wasn't entirely clear to me. I see that this file contains a whole bunch of other external files as well, and that it's properly linked to from the ScummVM doc on Libretro Docs. Closing this issue. thanks for clarifying.
