### ISSUE TITLE
Monkey Island Talkie Editions not working on Raspberry pi

### ISSUE THREAD

**Issue by hellricer** [libretro-mirrors/scummvm#197]
Talkie Editions created with the "MI1 Ultimate Talkie Edition Builder" don't work on Raspberry PI (retropie).

I know they're unofficial, but they work with this core on Linux perfectly.

**Comment by hellricer** [comment]
Update: Only OGG (`monster.sog`) doesn't work. The original `monster.sou` and FLAC `monster.sof` work.

This is probably an issue in RetroPie setup, not a bug in the code, so closing.

**Comment by grostim** [comment]
Same problem with le scummvm core on retroarch-arm64 for android tv.
