### ISSUE TITLE
Scummvm 2.6 for retroarch

### ISSUE THREAD

**Issue by ghost** [libretro-mirrors/scummvm#201]
Any chance of the latest version of scummvm 2.6?
The current one is not updated for a long time and many games do not work well, such as Blade Runner, or not work at all like Nightlong.

**Comment by hizzlekizzle** [comment]
See this issue: https://github.com/libretro/scummvm/issues/179

It's working and you can download it from the thread (or from https://github.com/hunterk/libretro_builds) but it's not integrated with our buildbot infrastructure yet.

**Comment by ghost** [comment]
@hizzlekizzle I know about it and use scummvm 2.7 git, but that's where the biggest problem is that it's not integrated with buildbot :) I often use the cores update check and then scummvm goes back to version 2.1. I will be grateful if you add version 2.7 someday.
One more detail in version 2.7 the option to set the themes doesn't work, or I'm doing something wrong.
I tried according to this description, but there is still a black background and green inscriptions :)
https://github.com/diablodiab/scummvm/issues/9

**Comment by hizzlekizzle** [comment]
You can "lock" a core to prevent it from being overwritten.

**Comment by ghost** [comment]
@hizzlekizzle thanks so much for the hint. I have set the core read-only and it works fine.

**Comment by schmurtzm** [comment]
The new scummvm core from diablodiab is awesome. I use it with the last dev source of ScummVM (currently in 2.7) , it works great and the list of compatibility is enormous comparing to the 2.1.1.
Easy to compile, this core benefits to the current very active work from the ScummVM team.

Clearly this core greatly extend the games compatibility list of Retroarch and deserve this update !

To respect the recommandations from ScummVM team (which doesn't support the libretro core but which is really helpful and reactive), there's some modifications to do and to explain in the way to launch a game on the scummVM core, I talk about it here : https://github.com/diablodiab/libretro-scummvm-backend/issues/24 . (I've also made a quick shell script to create the shortcuts automatically).

@elessar38 if you don't have the theme applied is not normal, it works fine on my side, just check that you have updated it with the script "bundle_aux_data.bash", then extract it and  then check your "extrapath"  in scummvm.ini : it must point on this path.

**Comment by elessar84** [comment]
I downloaded scummvm.zip from here:
https://build.bot.nu/assets/system/
I swapped it with retroarch and set the theme path in the emulator and it looks like it works as it should.
Issue can be closed. Thanks for help.
