### ISSUE TITLE
compile with zlib

### ISSUE THREAD

**Issue by legluondunet** [libretro-mirrors/scummvm#23]
Hello,

when I launch a game with Scummvm core, I have this error message:

"dxa cutscenes found, but  ScummVM has been buillt without zlib"

So no video played at start.

How to compile ScummVM core with Zlib?

**Comment by RobLoach** [comment]
I think this has been merged: https://github.com/libretro/scummvm/pull/22

**Comment by fetzerch** [comment]
@twinaphex this can be closed as well
