### ISSUE TITLE
Starting game from command line broken

### ISSUE THREAD

**Issue by RobLoach** [libretro-mirrors/scummvm#31]
[LIBRETRO_CMDLINE](https://github.com/libretro/scummvm/blob/master/LIBRETRO_CMDLINE) does not automatically load/start the game.

**Comment by gouchi** [comment]
Moreover, there is an inconsistency the core supported extensions are : exe, [scum](https://github.com/libretro/scummvm/blob/master/backends/platform/libretro/libretro.cpp#L99). But LIBRETRO_CMDLINE allows [scummvm](https://github.com/libretro/scummvm/blob/master/backends/platform/libretro/libretro.cpp#L205) extension file.
