### ISSUE TITLE
Setting RETRO_ENVIRONMENT_SET_SUPPORT_NO_GAME breaks autoload

### ISSUE THREAD

**Issue by diablodiab** [libretro-mirrors/scummvm#33]
It seems that this configuration now causes retro_load_game to be called with a NULL parameter even when a rom file is provided:
https://github.com/libretro/scummvm/blob/c49f31728a80694652df268ea54a3951a694af36/backends/platform/libretro/libretro.cpp#L30-L31

It doesn't look like this configuration was changed recently, so I'm thinking it's something in RetroArch that has been changed when handling the RETRO_ENVIRONMENT_SET_SUPPORT_NO_GAME configuration. Is this working as intended?

When I set it to false, autoload works again.

**Comment by gouchi** [comment]
I confirm setting it to false make autoload works again.

Will fix [issue](https://github.com/libretro/scummvm/issues/31).

**Comment by diablodiab** [comment]
This should be fixed by:
9e9cc3835f4fa0b82c21563c5134a05c5c948d46

**Comment by diablodiab** [comment]
This should be fixed by:
https://github.com/libretro/RetroArch/commit/9e9cc3835f4fa0b82c21563c5134a05c5c948d46

**Comment by gouchi** [comment]
Thank you it fixed it !

We need to decided which extension is correct (now both are working) for [libretro_cmdline](https://github.com/libretro/scummvm/blob/master/LIBRETRO_CMDLINE) [scum](https://github.com/libretro/scummvm/blob/master/backends/platform/libretro/libretro.cpp#L99) or [scummvm](https://github.com/libretro/scummvm/blob/master/backends/platform/libretro/libretro.cpp#L205) ?

**Comment by diablodiab** [comment]
The setting on line 205 is not about the extension, we just insert "scummvm" as the first parameter in argv to respect the normal syntax of argv where the first entry is the application itself.
https://github.com/libretro/scummvm/blob/master/backends/platform/libretro/libretro.cpp#L205

The extension is .scum

**Comment by gouchi** [comment]
Thank you, I misunderstood.

We can close this issue and #31
