### ISSUE TITLE
Save States crashing core

### ISSUE THREAD

**Issue by frthery** [libretro-mirrors/scummvm#4]
Hi,

I have compiled scummvm for my raspberry pi (it takes a very long time). After getting the .so file, i am launching emulator with command line and selecting dot (day of tentacle) game. The game is launching but after few minutes it is crashing, after investigation it was caused by auto savestates, by inactivating it no problem.
So save isn't possible. What should i do ?

No more informations with verbose mode, i only see a segmentation fault exception. A file is created tentacle-fr.s00 but i can't load it.

Thanks.

**Comment by diablodiab** [comment]
Segfaults when saving games and starting non-scummvm games on RPI are caused by the "localtime" function call in:
scummvm/backends/platform/libretro/os.cpp

**Comment by inactive123** [comment]
can we close this issue now?

**Comment by RobLoach** [comment]
This can be closed. No longer breaking when saving/loading states.

**Comment by fetzerch** [comment]
Can anyone close this please? @legluondunet, @RobLoach

**Comment by RobLoach** [comment]
Don't have Write access on here.

**Comment by legluondunet** [comment]
Don't have Write access on here.
