### ISSUE TITLE
path parameter in scummvm file clips

### ISSUE THREAD

**Issue by zach-morris** [libretro-mirrors/scummvm#45]
I've found an issue when attempting to launch a game using a scummvm file.  I've tried the following with the game 'tentacle' in two different locations on my machine:

Try 1 (works):
Path to game: `/Users/Zach/tentacle`
Scummvm file:
`-p "/Users/Zach/tentacle" tentacle`

Try 2 (fails):
Path to game:  `/Users/Zach/Library/Application Support/Kodi/userdata/addon_data/plugin.program.iarl/temp_iarl/tentacle`
Scummvm file:
`-p "/Users/Zach/Library/Application Support/Kodi/userdata/addon_data/plugin.program.iarl/temp_iarl/tentacle" tentacle`

Launching from the command line, verbose output says:
`scummvm: Non-existent game path '/Users/Zach/Library/Application Support/Kodi/userdata/addon_data/plugin.program.iarl/temp_iarl/tentatentacle'`

The game files and folder is the same, except in a different directory.  It appears the path parameter is being clipped?  Is there a max length to the parameter or file somehow?

**Comment by RobLoach** [comment]
What is the ScummVM file named? `tentacle.scummvm`? This happens over at:
https://github.com/libretro/scummvm/blob/master/backends/platform/libretro/libretro.cpp#L210

As an alternative, you could try loading one of the files in the tentacle directory:
https://github.com/libretro/scummvm/blob/master/LIBRETRO_CMDLINE.md

`retroarch -L scummvm_libretro.so /Users/Zach/tentacle/TENTACLE.000`

**Comment by zach-morris** [comment]
Yeah, the files in the directory 'tentacle' are as follows:
`MONSTER.SOU
TENTACLE.000
TENTACLE.001
tentacle.scummvm`

With the text in the scummvm file as shown above.   Attempting to load TENTACLE.001 has the same issue for some strange reason (works with the short length directory, fails for the long length directory).  The only error I see is the 'Non-existent game path' error.

I tried loading the scummvm and TENTACLE.001 files from the GUI and the GUI crashes when attempting to load the file from the long length directory, but works when using the short length directory.

**Comment by RobLoach** [comment]
> I tried loading the scummvm and TENTACLE.001 files from the GUI and the GUI crashes when attempting to load the file from the long length directory, but works when using the short length directory.

Interesting... In [libretro.c](https://github.com/libretro/scummvm/blob/master/backends/platform/libretro/libretro.cpp#L224) is looks like there is only 200 characters to work with. Think it may be cropping the long path?

The options to load are listed in [LIBRETRO_CMDLINE.md](https://github.com/libretro/scummvm/blob/master/LIBRETRO_CMDLINE.md). You either load the .scummvm file, or a file from within the `tentacle` directory.

**Comment by zach-morris** [comment]
Yeah, that maximum number is most likely the cause (although I can't count 200 characters in my case).  Is there any reason for the 200 limit?  Given the [other command line options](http://wiki.scummvm.org/index.php/User_Manual/Appendix:_Command_line_options) you can send with a scummvm file, seems like 200 could potentially be too short in some cases.

**Comment by RobLoach** [comment]
The 200 character limit [was put there by @diablodiab](https://github.com/libretro/scummvm/commit/cfe99e95ab576b34612b48f183e364a7d624a7f2#diff-8b1f351f423e02ac0281cc9a4ecabdd0R214) when he originally wrote the code. Feel free to double that in a PR. Then we'll be able to test it out with the increased limit.

Looks like there's also `static char cmd_params[20][100];` which seems suspicious.

**Comment by zach-morris** [comment]
That fixed it.  Thanks!
