### ISSUE TITLE
Update LaunchPad

### ISSUE THREAD

**Issue by RobLoach** [libretro-mirrors/scummvm#46]
https://code.launchpad.net/~libretro/+recipe/scummvm-libretro-daily

Last build was 2016-05-10. May be good to switch to git:
https://help.launchpad.net/Code/Git

@sergiobenrocha2, I could help out in keeping this up and running. Let me know.

**Comment by sergiobenrocha2** [comment]
I'm updating that, thanks.

There's no automatic import / mirror feature on launchpad with git repos yet... and using git is a little bit more complicated there. I can add you in the team, so you can sync manually the repo with "git pull & bzr commit & bzr push" when you feel it needs a update, just let me know.

**Comment by RobLoach** [comment]
Thanks a lot!

>  I can add you in the team, so you can sync manually

I'd appreciate that! I'm https://launchpad.net/~robloach on there.

**Comment by sergiobenrocha2** [comment]
Nice, so you can update that cores you broke :D 

Approved

**Comment by RobLoach** [comment]
:ghost:
