### ISSUE TITLE
Update to ScummVM 1.9.0

### ISSUE THREAD

**Issue by RobLoach** [libretro-mirrors/scummvm#48]
http://scummvm.org/news/20161017/
http://scummvm.org/frs/scummvm/1.9.0/ReleaseNotes

**Comment by RobLoach** [comment]
Tried this update over at:
https://github.com/libretro/scummvm/compare/master...RobLoach:scummvm-1.9.0

Getting the following error:
```
/usr/bin/ld: base/libbase.a(main.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
base/libbase.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile.common:150: recipe for target 'scummvm_libretro.so' failed
make: *** [scummvm_libretro.so] Error 1
```

Know what's going on?

**Comment by fetzerch** [comment]
@RobLoach I've seen your post too late, would you be interested in testing https://github.com/fetzerch/scummvm/commits/update-1.9.0 it does the update and enables more cores.
Works for me on linux. Compile tested also on windows and osx.

**Comment by RobLoach** [comment]
Nicely done!
