### ISSUE TITLE
New Nightly build

### ISSUE THREAD

**Issue by NelsonRosenberg** [libretro-mirrors/scummvm#66]
The last nightly build available is from November. There were quite a few nice updates like VOG and FLAC to the master branch. Could we get an update build? 

Also, would it be possible to have a build with the experimental scummvm cores?

I know we can build it ourselves, but most don't have the tools or the knowledge (I tried, but got errors during build and don't have the tools to debug it in windows).

Thank you.

**Comment by RobLoach** [comment]
Attempted an update to ScummVM to 1.10git over at https://github.com/RobLoach/scummvm/pull/1 .
