### ISSUE TITLE
"Make" Returns Error

### ISSUE THREAD

**Issue by geektbee** [libretro-mirrors/scummvm#73]
I attempted to follow the guide at
[http://wiki.scummvm.org/index.php/Compiling_ScummVM/GCC](http://wiki.scummvm.org/index.php/Compiling_ScummVM/GCC), but am getting the error below. I only have minimal programming experience in these kind of programs, but I did try to fix it myself, by modifying and hardcoding the paths to the files the process was looking for. It didn't do anything for me in the long run, though. The boolean.h file definitely there, so I don't fully understand what it's deal is. I've tried compiling on Manjaro and Fedora, with the same results each time.

```
C++		backends/fs/posix/posix-fs.o
In file included from backends/fs/posix/posix-fs.cpp:35:0:
backends/fs/posix/../../platform/libretro/libretro-common/include/retro_dirent.h:26:10: fatal error: boolean.h: No such file or directory
 #include <boolean.h>
          ^~~~~~~~~~~
compilation terminated.
```

My endgoal here is to get the most recent version of _scummvm_libretro.so_, so if I'm going about wrong, and looking in the wrong place, someone please let me know. I'm trying to self-fix the issue I reported in the [ScummVM Issues: #177](https://github.com/libretro/Lakka-LibreELEC/issues/177)

**Comment by RobLoach** [comment]
To compile the libretro ScummVM core...

```
cd backends/platform/libretro
make
```

**Comment by geektbee** [comment]
...
I must be missing something.... do we need to wait for make and makefile to be added in later for this to work? Or am I cloning the wrong .git?

```
make: *** No targets specified and no makefile found.   Stop.
```

**Comment by RobLoach** [comment]
Oops, missed the build directory...

```
cd backends/platform/libretro/build
make
```

**Comment by geektbee** [comment]
Unsuccessfully compiled on the Fedora box, but successfully compiled on the Manjaro box. I transferred it to the Lakka OS /storage/cores, and all the ScummVM games are working well now! Thank you!!

**Comment by RobLoach** [comment]
What error did you get on Fedora?

**Comment by geektbee** [comment]
Something about needing to compile with -fPIC parameter.
I can run it again and see the exact message if you give me some time.

**Comment by RobLoach** [comment]
Yeah, that kind of stuff is above my knowledge. The makefile is voodoo magic.

**Comment by geektbee** [comment]
Hmm... this time it was successful. I guess I had needed a clean clone; we're all good, it seems! Thanks again for all of your guidance!
