### ISSUE TITLE
chivalry-win doesn't work

### ISSUE THREAD

**Issue by newoski** [libretro-mirrors/scummvm#84]

**Comment by fetzerch** [comment]
Can you please try again once builds with v2.0.0 are available and report back?

**Comment by newoski** [comment]
Will do

**Comment by RobLoach** [comment]
@newoski Work? I got Gabriel Knight to work :+1:

**Comment by newoski** [comment]
Doing a core update now and then testing... latest core includes 2.0 updates?

**Comment by newoski** [comment]
No progress on Chivalry is Not Dead. Game Data Not Found error. If I load the scummvm file directly, via RocketLauncher (game launcher) it works for a split second, but then crashes RA. If I load the core, start the core, and then load the game from the game list, it crashes immediately

**Comment by newoski** [comment]
Making progress, here. wintermute.zip is required. i'll update when I have it working

**Comment by newoski** [comment]
So now it works via RetroArch GUI/ScummVM GUI in RA, but not via command line. Every time I run it via command line, it recreates the ScummVM file, in my rom directory, but then failes about Game Data Not Found. Moving the ScummVM file to the game directory has no impact. Odd

**Comment by RobLoach** [comment]
What command do you use? When you run it with --verbose, what log do you get? What file are you launching?

**Comment by newoski** [comment]
retroarch.exe --verbose "E:\ScummVM\chivalry-win.scummvm" -f -c "D:\Arcade\Emulators\RetroArch\config\SCUMMVM.cfg" -L "D:\Arcade\Emulators\RetroArch\cores\scummvm_libretro.dll"

Log: https://pastebin.com/p6mB4gnq

**Comment by newoski** [comment]
Disregard. This one is fixed

**Comment by RobLoach** [comment]
I'll update the ScummVM.dat to have all engines/games in there too.

**Comment by newoski** [comment]
So the way I solved it, was by switching my command line to "chivalry.scummvm" instead of "chivalry-win.scummvm". Not sure why that had an impact, but it did. The short name, per ScummVM, includes the win. Odd, but working now. Not sure if this bug should be open or closed
