### ISSUE TITLE
Please delete the ScummVM IRC channel from your .travis.yml

### ISSUE THREAD

**Issue by csnover** [libretro-mirrors/scummvm#88]
Hi,

It looks like you guys have enabled Travis builds for this repo. Your build failures are being sent into our (ScummVM’s) channel because you haven’t updated `.travis.yml` before turning it on for this repository. Could you please fix this? Thanks!

**Comment by inactive123** [comment]
Our bad.

@RobLoach @bparker06 could you look into this and help out upstream? Thanks.

**Comment by RobLoach** [comment]
Thanks for the note, @csnover https://github.com/libretro/scummvm/pull/89

**Comment by RobLoach** [comment]
This is done. Thanks, all!
