### ISSUE TITLE
The bizarre adventures of woodruff and the schnibble has some sound synchronization problems

### ISSUE THREAD

**Issue by i30817** [libretro-mirrors/scummvm#97]
This doesn't happen in the recent 2.0 ppa from [here](https://launchpad.net/~samoilov-lex/+archive/ubuntu/retrogames/+packages?field.name_filter=scummvm&field.status_filter=published&field.series_filter=)

**Comment by NelsonRosenberg** [comment]
Sound synchronization  looks like a very mild description of the bug, at least for me. The game cuts the sound short after one or two words, and the speaking animation is sped-up quite a lot making the game almost unplayable as you don't even have time to read the subtitles. It does work in standalone scummvm.

**Comment by i30817** [comment]
Yes, that is correct iirc.

**Comment by jdgleaver** [comment]
This should be fixed by commit 09c856d7751bcfa67cff6474a0e74957a6f1582b

:slightly_smiling_face:

**Comment by NelsonRosenberg** [comment]
Thanks a lot @jdgleaver !
